LAPTOP_VENDOR_PATH=/sys/class/dmi/id/sys_vendor
LAPTOP_MODEL_PATH=/sys/class/dmi/id/product_name
MB_NAME_PATH=/sys/class/dmi/id/board_name
CPU_INFO_PATH=/proc/cpuinfo
RAM_INFO_PATH=/tmp/dram_raw.txt

